// Comprehensive dummy data for Spend Analytix application

export const suppliers = [
  {
    id: 1,
    name: "TechCorp Solutions",
    category: "IT Services",
    spend: 2400000,
    performance: 85,
    relationship: "Strategic",
    location: "San Francisco, CA",
    contact: "john.doe@techcorp.com",
    phone: "+1 (555) 123-4567",
    contracts: 3,
    riskLevel: "Medium",
    complianceRate: 85,
    breaches: 3,
    lastPayment: "2024-01-15",
    paymentTerms: 30,
    qualityScore: 88,
    deliveryScore: 82,
    innovationIndex: 90,
  },
  {
    id: 2,
    name: "Global Manufacturing Inc",
    category: "Raw Materials",
    spend: 1800000,
    performance: 92,
    relationship: "Preferred",
    location: "Detroit, MI",
    contact: "sarah.smith@globalmfg.com",
    phone: "+1 (555) 234-5678",
    contracts: 2,
    riskLevel: "Low",
    complianceRate: 92,
    breaches: 1,
    lastPayment: "2024-01-20",
    paymentTerms: 45,
    qualityScore: 95,
    deliveryScore: 89,
    innovationIndex: 75,
  },
  {
    id: 3,
    name: "Office Supplies Plus",
    category: "Office Supplies",
    spend: 450000,
    performance: 65,
    relationship: "Transactional",
    location: "Chicago, IL",
    contact: "mike.jones@officesupplies.com",
    phone: "+1 (555) 345-6789",
    contracts: 1,
    riskLevel: "High",
    complianceRate: 65,
    breaches: 8,
    lastPayment: "2024-01-10",
    paymentTerms: 30,
    qualityScore: 70,
    deliveryScore: 60,
    innovationIndex: 45,
  },
  {
    id: 4,
    name: "Logistics Partners",
    category: "Transportation",
    spend: 890000,
    performance: 78,
    relationship: "Preferred",
    location: "Atlanta, GA",
    contact: "lisa.brown@logistics.com",
    phone: "+1 (555) 456-7890",
    contracts: 2,
    riskLevel: "Medium",
    complianceRate: 78,
    breaches: 4,
    lastPayment: "2024-01-18",
    paymentTerms: 30,
    qualityScore: 80,
    deliveryScore: 76,
    innovationIndex: 65,
  },
  {
    id: 5,
    name: "Energy Solutions Ltd",
    category: "Utilities",
    spend: 1200000,
    performance: 95,
    relationship: "Strategic",
    location: "Houston, TX",
    contact: "david.wilson@energysol.com",
    phone: "+1 (555) 567-8901",
    contracts: 1,
    riskLevel: "Low",
    complianceRate: 95,
    breaches: 0,
    lastPayment: "2024-01-22",
    paymentTerms: 60,
    qualityScore: 98,
    deliveryScore: 92,
    innovationIndex: 88,
  },
]

export const contracts = [
  {
    id: 1,
    supplierId: 1,
    supplierName: "TechCorp Solutions",
    value: 2400000,
    startDate: "2023-01-01",
    endDate: "2024-12-31",
    status: "Active",
    compliance: 85,
    breaches: 3,
    leakage: 45000,
    category: "IT Services",
    paymentTerms: 30,
    renewalDate: "2024-10-01",
    autoRenewal: true,
  },
  {
    id: 2,
    supplierId: 2,
    supplierName: "Global Manufacturing Inc",
    value: 1800000,
    startDate: "2023-06-01",
    endDate: "2025-06-15",
    status: "Active",
    compliance: 92,
    breaches: 1,
    leakage: 12000,
    category: "Raw Materials",
    paymentTerms: 45,
    renewalDate: "2025-03-01",
    autoRenewal: false,
  },
  {
    id: 3,
    supplierId: 3,
    supplierName: "Office Supplies Plus",
    value: 450000,
    startDate: "2023-10-01",
    endDate: "2024-09-30",
    status: "Review",
    compliance: 65,
    breaches: 8,
    leakage: 89000,
    category: "Office Supplies",
    paymentTerms: 30,
    renewalDate: "2024-07-01",
    autoRenewal: false,
  },
]

export const invoices = [
  {
    id: "INV-2024-001",
    supplierId: 1,
    supplierName: "TechCorp Solutions",
    amount: 125000,
    date: "2024-01-15",
    dueDate: "2024-02-14",
    status: "Paid",
    category: "IT Services",
    description: "Monthly IT support services",
    paymentDate: "2024-02-10",
    discountTaken: 2500,
    lateFee: 0,
  },
  {
    id: "INV-2024-002",
    supplierId: 2,
    supplierName: "Global Manufacturing Inc",
    amount: 89000,
    date: "2024-01-20",
    dueDate: "2024-03-05",
    status: "Pending",
    category: "Raw Materials",
    description: "Steel components Q1 delivery",
    paymentDate: null,
    discountTaken: 0,
    lateFee: 0,
  },
  {
    id: "INV-2024-003",
    supplierId: 3,
    supplierName: "Office Supplies Plus",
    amount: 15000,
    date: "2024-01-10",
    dueDate: "2024-02-09",
    status: "Overdue",
    category: "Office Supplies",
    description: "Office supplies monthly order",
    paymentDate: null,
    discountTaken: 0,
    lateFee: 450,
  },
]

export const leakages = [
  {
    id: 1,
    type: "Post-contract price increases",
    amount: 340000,
    impact: "High",
    trend: "Increasing",
    supplierId: 1,
    supplierName: "TechCorp Solutions",
    category: "IT Services",
    dateIdentified: "2024-01-15",
    status: "Under Review",
  },
  {
    id: 2,
    type: "Unauthorized purchases",
    amount: 156000,
    impact: "Medium",
    trend: "Stable",
    supplierId: null,
    supplierName: "Multiple Suppliers",
    category: "Various",
    dateIdentified: "2024-01-10",
    status: "Action Required",
  },
  {
    id: 3,
    type: "Duplicate payments",
    amount: 89000,
    impact: "Medium",
    trend: "Decreasing",
    supplierId: 3,
    supplierName: "Office Supplies Plus",
    category: "Office Supplies",
    dateIdentified: "2024-01-08",
    status: "Resolved",
  },
  {
    id: 4,
    type: "Late payment penalties",
    amount: 23000,
    impact: "Low",
    trend: "Stable",
    supplierId: null,
    supplierName: "Various Suppliers",
    category: "Various",
    dateIdentified: "2024-01-05",
    status: "Monitoring",
  },
]

export const categories = [
  {
    name: "IT Services",
    spend: 3200000,
    budget: 3500000,
    growth: 12,
    suppliers: 8,
    risk: "Medium",
    contracts: 12,
    compliance: 85,
    topSupplier: "TechCorp Solutions",
  },
  {
    name: "Raw Materials",
    spend: 2800000,
    budget: 3000000,
    growth: 8,
    suppliers: 12,
    risk: "Low",
    contracts: 8,
    compliance: 92,
    topSupplier: "Global Manufacturing Inc",
  },
  {
    name: "Professional Services",
    spend: 1500000,
    budget: 1400000,
    growth: 15,
    suppliers: 6,
    risk: "High",
    contracts: 6,
    compliance: 78,
    topSupplier: "Consulting Partners LLC",
  },
  {
    name: "Office Supplies",
    spend: 800000,
    budget: 900000,
    growth: -3,
    suppliers: 4,
    risk: "High",
    contracts: 4,
    compliance: 65,
    topSupplier: "Office Supplies Plus",
  },
  {
    name: "Transportation",
    spend: 900000,
    budget: 800000,
    growth: 5,
    suppliers: 3,
    risk: "Medium",
    contracts: 3,
    compliance: 78,
    topSupplier: "Logistics Partners",
  },
]

export const performanceMetrics = {
  monthly: [
    { month: "Jan", performance: 82, compliance: 85, satisfaction: 78, spend: 750000 },
    { month: "Feb", performance: 85, compliance: 87, satisfaction: 82, spend: 820000 },
    { month: "Mar", performance: 83, compliance: 89, satisfaction: 85, spend: 780000 },
    { month: "Apr", performance: 87, compliance: 91, satisfaction: 88, spend: 890000 },
    { month: "May", performance: 89, compliance: 93, satisfaction: 90, spend: 920000 },
    { month: "Jun", performance: 91, compliance: 95, satisfaction: 92, spend: 950000 },
  ],
  quarterly: [
    { quarter: "Q1 2023", performance: 78, compliance: 82, satisfaction: 75, spend: 2100000 },
    { quarter: "Q2 2023", performance: 82, compliance: 85, satisfaction: 80, spend: 2300000 },
    { quarter: "Q3 2023", performance: 85, compliance: 88, satisfaction: 83, spend: 2450000 },
    { quarter: "Q4 2023", performance: 87, compliance: 90, satisfaction: 86, spend: 2600000 },
    { quarter: "Q1 2024", performance: 89, compliance: 92, satisfaction: 89, spend: 2750000 },
  ],
}

export const cashFlow = [
  { month: "Jan", inflow: 2800000, outflow: 2400000, net: 400000 },
  { month: "Feb", inflow: 3200000, outflow: 2800000, net: 400000 },
  { month: "Mar", inflow: 2900000, outflow: 3100000, net: -200000 },
  { month: "Apr", inflow: 3400000, outflow: 2900000, net: 500000 },
  { month: "May", inflow: 3100000, outflow: 2700000, net: 400000 },
  { month: "Jun", inflow: 3300000, outflow: 2950000, net: 350000 },
]

export const savingsOpportunities = [
  {
    id: 1,
    opportunity: "Early payment discounts",
    potential: 45000,
    effort: "Low",
    timeline: "Immediate",
    category: "Payment Terms",
    description: "Negotiate early payment discounts with key suppliers",
    roi: "High",
  },
  {
    id: 2,
    opportunity: "Contract renegotiation",
    potential: 180000,
    effort: "High",
    timeline: "3-6 months",
    category: "Contract Management",
    description: "Renegotiate terms with underperforming suppliers",
    roi: "Very High",
  },
  {
    id: 3,
    opportunity: "Supplier consolidation",
    potential: 95000,
    effort: "Medium",
    timeline: "2-4 months",
    category: "Sourcing",
    description: "Consolidate suppliers in fragmented categories",
    roi: "High",
  },
  {
    id: 4,
    opportunity: "Process automation",
    potential: 120000,
    effort: "Medium",
    timeline: "4-8 months",
    category: "Operations",
    description: "Automate invoice processing and approval workflows",
    roi: "High",
  },
]

export const alerts = [
  {
    id: 1,
    type: "warning",
    severity: "Medium",
    message: "Office Supplies category showing 22% contract breach rate",
    category: "Office Supplies",
    date: "2024-01-15",
    status: "Open",
    assignee: "Category Manager",
  },
  {
    id: 2,
    type: "info",
    severity: "Low",
    message: "IT Services spend increased 12% this quarter",
    category: "IT Services",
    date: "2024-01-14",
    status: "Acknowledged",
    assignee: "Finance Manager",
  },
  {
    id: 3,
    type: "danger",
    severity: "High",
    message: "Professional Services has 3 suppliers with performance issues",
    category: "Professional Services",
    date: "2024-01-13",
    status: "In Progress",
    assignee: "Sourcing Manager",
  },
  {
    id: 4,
    type: "warning",
    severity: "Medium",
    message: "TechCorp Solutions exceeded contract terms by 18% in Q4",
    category: "IT Services",
    date: "2024-01-12",
    status: "Under Review",
    assignee: "Contract Manager",
  },
]

export const riskAssessments = [
  {
    supplierId: 3,
    supplierName: "Office Supplies Plus",
    risk: "High",
    issues: ["Payment delays", "Quality concerns", "Contract breaches"],
    impact: "Medium",
    mitigation: "Consider alternative suppliers",
    lastReview: "2024-01-15",
  },
  {
    supplierId: 1,
    supplierName: "TechCorp Solutions",
    risk: "Medium",
    issues: ["Price volatility", "Capacity constraints"],
    impact: "High",
    mitigation: "Diversify IT service providers",
    lastReview: "2024-01-10",
  },
  {
    supplierId: 4,
    supplierName: "Logistics Partners",
    risk: "Medium",
    issues: ["Geographic concentration"],
    impact: "Low",
    mitigation: "Identify backup transportation options",
    lastReview: "2024-01-08",
  },
  {
    supplierId: 2,
    supplierName: "Global Manufacturing Inc",
    risk: "Low",
    issues: ["Minor delivery delays"],
    impact: "Low",
    mitigation: "Monitor delivery performance",
    lastReview: "2024-01-05",
  },
]
